---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-logrotate"
      include_role:
        name: "ansible-role-logrotate"
      vars:
        logrotate_entries:
          - name: nginx
            paths:
              - /var/log/nginx/*.log
            options:
              - create 0644 root
              - size 100M
              - rotate 7
              - compress
              - notifempty
              - prerotate
                    echo "start rotation for $1 $(date)" >> /tmp/rotation.log
                endscript
              - postrotate
                    echo "complete rotation for $1 $(date)" >> /tmp/rotation.log
                endscript

          - name: rsyslog
            paths:
              - /var/log/kern.log
              - /var/log/message
              - /var/log/debug
            options:
              - weekly
              - rotate 4
              - compress
              - size 100M
