---
- name: Verify
  hosts: all
  tasks:
    - name: Linux | Logrotate should be present
      command: logrotate --help
      register: logrotate_status

    - name: Linux | Logrotate should be functionnal
      command: logrotate -f /etc/logrotate.conf
      register: logrotate_config

    - name: Linux | Verify commands outputs
      assert:
        that:
          - logrotate_status.rc == 0
          - logrotate_config.rc == 0
        success_msg: "All tests passed"
